### PR TITLE
Disable DBUS hole for notifications which should no longer be needed

### PR DESCRIPTION
**Pull request by darkdragon-001**
@bbhtt can you please test this?

### CODE REVIEW

**Comment by bbhtt** [comment]
How does notification in the app work? I couldn't find a way to trigger one.

But one way to test it would be:

```
$ flatpak run --command=sh io.kopia.KopiaUI

notify-send test

(notify-send:4): libnotify-WARNING **: 13:08:28.756: Running in confined mode, using Portal notifications. Some features and hints won't be supported
libnotify-Message: 13:08:28.756: Category is not available when using Portal Notifications
libnotify-Message: 13:08:28.756: App Name is not available when using Portal Notifications

```

And it'll show a notification.

**Comment by darkdragon-001** [comment]
This is why I was asking as I didn't know how to trigger a notification myself :roll_eyes: 

So I guess it works. Thanks for your suggestion, I will go and merge it.

**Comment by bbhtt** [comment]
Hey @darkdragon-001 we fixed a bug in libnotify that was causing applications on Electron baseapp 23.08 to crash https://github.com/flathub/org.electronjs.Electron2.BaseApp/pull/48

If you can trigger a rebuild via https://buildbot.flathub.org/#/ it'd be great.

**Comment by darkdragon-001** [comment]
@bbhtt I triggered a rebuild at https://buildbot.flathub.org/#/builders/6/builds/72190.

**Pull request merged**
